### PR TITLE
Add documentation for using the widget with Wordpress

### LINKED ISSUE #55: auto-format
This came up at the p5.js working group meeting via @lmccart.  Might be good to have "auto-format" with CMD-T in the widget (same as current desktop editor.)

### LINKED ISSUE #56: unwanted html in the code/ wordpress
This widget has been incredibly helpful for the signing coders workshop. Much thanks to Atul.
One problem I've been having is specific to use in wordpress blog. I think this might be wordpress-specific issue, with a reasonable workaround. However, I think it's worth pointing out for future use. 

My use cas scenario has been: write some code in the p5 desktop editor and paste it in the wordpress Text mode. 

image

and the <p> and </p> shows up in side of the widget. 
image

I've been able to manage so far by manually deleting it, but it's hard to find out where they are. Not having full control over the code results in some awkward code structures. This is related to the previous[ issue.](https://github.com/toolness/p5.js-widget/issues/55)

### PR DESCRIPTION
**Pull request by kaganjd**
Fixes #56.

### CODE REVIEW

**Comment by kaganjd** [comment]
I wasn't really able to check this—my formatting looked really weird in the browser, even though I deleted and re-cloned the repo—so it's worth checking manually. I'm happy to make any edits.

**Comment by toolness** [comment]
This looks great, thanks! I've made a few minor changes and filed them as a PR to this PR:

https://github.com/kaganjd/p5.js-widget/pull/1

Um, I guess I should have just made comments on this PR instead, but too late now.  If you think they look OK feel free to merge that PR, and then I'll merge this one!

**Comment by toolness** [comment]
woooot thanks!!

**Comment by kaganjd** [comment]
@toolness  Gah, I think I did some weird Git stuff before you merged and the changes didn't get in. On my master, I did `git cherry-pick <your commit>` and pushed that up. Should I open another PR against your master? Or you wanna cherry-pick on your end? Sorry about this :-/

**Comment by toolness** [comment]
No worries, I ended up cherry-picking on my end :)

**Pull request merged**
